title: GeoWAM
author: Andreas Fritz
email: geowam@disy.net
description: > # this means to ignore newlines until "baseurl:"
  Neue Geodaten zur Verbesserung des Wassermanagements tidebeeinflusster KuÌˆstenbereiche

# social links
twitter_username: your-twitter-handle
github_username:  frischerfritz

show_excerpts: true # set to false to remove excerpts on the homepage


theme: jekyll-theme-cayman
